name: Build and Test Spring Boot Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project sources
      uses: actions/checkout@v4

    - name: Setup JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Make Gradlew Executable
      run: chmod +x gradlew

    - name: Run build with Gradle Wrapper
      run: ./gradlew build

    - name: Run tests with Gradle Wrapper
      run: ./gradlew test

    - name: Run Spring Boot application
      run: ./gradlew bootRun &
      env:
        SPRING_PROFILES_ACTIVE: test

    - name: Wait for Spring Boot to start
      run: |
        echo "Waiting for Spring Boot to start..."
        sleep 30

    - name: Run integration tests
      run: ./gradlew integrationTest