name: Java CI with Gradle

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Test with Gradle Wrapper
      run: gradlew clean test

    - name: Build with Gradle Wrapper
      run: gradlew build

  dependency-submission:

    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v3.1.0