name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permissions for gradlew
      run: chmod +x gradlew.bat

    - name: Build with Gradle Wrapper
      run: ./gradlew.bat build

    - name: Test with Gradle Wrapper
      run: ./gradlew.bat test